const fs = require('fs');
let content = fs.readFileSync('app/settings/page.tsx', 'utf8');

const dictionary = 
  const t = {
    en: {
      settings: 'Settings',
      profile: 'Profile & Account',
      manageId: 'Manage your identity',
      appearance: 'Appearance',
      theme: 'Dark/Light Theme',
      notifications: 'Notifications',
      alerts: 'Alerts, Chimes & Offers',
      appLang: 'App Language',
      english: 'English',
      privacy: 'Privacy & Data',
      security: 'Security & Telemetry',
      devConsole: 'Developer Console',
      advDebug: 'Advanced debugging',
      signOut: 'Sign Out',
      proximity: 'Proximity Chimes',
      proxDesc: 'Vibrate when bus is near',
      deviations: 'Route Deviations',
      devDesc: 'Alert me if bus takes detour',
      marketing: 'Marketing Offers',
      markDesc: 'Pass discounts & promos',
      dataSecured: 'Your data is secured with AES-256 encryption.',
      liveLoc: 'Live Location Telemetry',
      liveLocDesc: 'Used for crowd-sourcing ETAs',
      camAccess: 'Camera Access',
      camDesc: 'Required for OCR uploads',
      delAcc: 'Delete My Account & Data'
    },
    kn: {
      settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      profile: 'ಪ್ರೊಫೈಲ್ ಮತ್ತು ಖಾತೆ',
      manageId: 'ನಿಮ್ಮ ಗುರುತನ್ನು ನಿರ್ವಹಿಸಿ',
      appearance: 'ಗೋಚರತೆ',
      theme: 'ಡಾರ್ಕ್/ಲೈಟ್ ಥೀಮ್',
      notifications: 'ಅಧಿಸೂಚನೆಗಳು',
      alerts: 'ಎಚ್ಚರಿಕೆಗಳು, ಕೊಡುಗೆಗಳು',
      appLang: 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ',
      english: 'ಆಂಗ್ಲ',
      privacy: 'ಗೌಪ್ಯತೆ ಮತ್ತು ಡೇಟಾ',
      security: 'ಭದ್ರತೆ ಮತ್ತು ಟೆಲಿಮೆಟ್ರಿ',
      devConsole: 'ಡೆವಲಪರ್ ಕನ್ಸೋಲ್',
      advDebug: 'ಸುಧಾರಿತ ಡಿಬಗ್ಗಿಂಗ್',
      signOut: 'ಸೈನ್ ಔಟ್',
      proximity: 'ಸಾಮೀಪ್ಯ ಚೈಮ್ಸ್',
      proxDesc: 'ಬಸ್ ಹತ್ತಿರವಿರುವಾಗ ಕಂಪಿಸಿ',
      deviations: 'ಮಾರ್ಗ ವಿಚಲನಗಳು',
      devDesc: 'ಬಸ್ ಮಾರ್ಗ ಬದಲಿಸಿದರೆ ಎಚ್ಚರಿಸಿ',
      marketing: 'ಮಾರ್ಕೆಟಿಂಗ್ ಕೊಡುಗೆಗಳು',
      markDesc: 'ಪಾಸ್ ರಿಯಾಯಿತಿಗಳು',
      dataSecured: 'ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಸುರಕ್ಷಿತಗೊಳಿಸಲಾಗಿದೆ.',
      liveLoc: 'ಲೈವ್ ಸ್ಥಳ',
      liveLocDesc: 'ETA ಗಳಿಗಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ',
      camAccess: 'ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶ',
      camDesc: 'OCR ಗಾಗಿ ಅಗತ್ಯವಿದೆ',
      delAcc: 'ನನ್ನ ಖಾತೆಯನ್ನು ಅಳಿಸಿ'
    },
    hi: {
      settings: 'सेटिंग्स',
      profile: 'प्रोफ़ाइल और खाता',
      manageId: 'अपनी पहचान प्रबंधित करें',
      appearance: 'दिखावट',
      theme: 'डार्क/लाइट थीम',
      notifications: 'सूचनाएं',
      alerts: 'अलर्ट, चाइम्स और ऑफ़र',
      appLang: 'ऐप की भाषा',
      english: 'अंग्रेज़ी',
      privacy: 'गोपनीयता और डेटा',
      security: 'सुरक्षा और टेलीमेट्री',
      devConsole: 'डेवलपर कंसोल',
      advDebug: 'उन्नत डिबगिंग',
      signOut: 'साइन आउट',
      proximity: 'प्रॉक्सिमिटी चाइम्स',
      proxDesc: 'बस पास होने पर वाइब्रेट करें',
      deviations: 'रूट विचलन',
      devDesc: 'बस के रास्ता बदलने पर अलर्ट करें',
      marketing: 'मार्केटिंग ऑफ़र',
      markDesc: 'पास छूट और प्रोमो',
      dataSecured: 'आपका डेटा सुरक्षित है।',
      liveLoc: 'लाइव लोकेशन',
      liveLocDesc: 'ईटीए के लिए उपयोग किया जाता है',
      camAccess: 'कैमरा एक्सेस',
      camDesc: 'ओसीआर के लिए आवश्यक',
      delAcc: 'मेरा खाता हटाएं'
    }
  };
;

// Insert dictionary right after lang state
content = content.replace(/const \[lang, setLang\] = useState\(" en\\);/,
